### ISSUE TITLE
Wallpaper isn't set initially when starting flowy

### ISSUE THREAD

**Issue by Aloso** [vineetred/flowy#10]
**Describe the bug**
The wallpaper is updated at certain times of the day, but is in _not_ updated when initially starting `flowy`.

**To Reproduce**
1. Run `flowy -p lake`

**Expected behavior**
The wallpaper changes

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - DE: KDE 5.70.0 / Plasma 5.18.5
 - WM: KWin
 - Version: `master` branch

**Comment by amr3k** [comment]
I can confirm this with the same specs (Manjaro KDE)
