### ISSUE TITLE
Place config file in appropriate place

### ISSUE THREAD

**Issue by Aloso** [vineetred/flowy#11]
Configuration files should be placed in the appropriate location depending on the OS. For example, on Linux, it should be in `~/.config`.

I recommend to use the [directories-next](https://docs.rs/directories-next/1.0.1/directories_next/) crate for this.

**Comment by vineetred** [comment]
Do you think you can work on this issue?

**Comment by Aloso** [comment]
Yes, this should be straightforward to implement. I'll make a PR.

**Comment by Aloso** [comment]
Should downloaded wallpapers be in the `.config` folder as well? I think yes, so they don't pollute the current working directory.

**Comment by vineetred** [comment]
I think yes, that would be ideal. Will keep them hidden from the user's visible directories at least.
