### ISSUE TITLE
Split setting the wallpaper into separate crate

### ISSUE THREAD

**Issue by Aloso** [vineetred/flowy#15]
As I mentioned in https://github.com/vineetred/flowy/issues/6#issuecomment-655078842, it would be ideal if the functionality for setting the wallpaper was moved to a new crate.

A similar crate, [`wallpaper`](https://github.com/reujab/wallpaper.rs), already exists, but it appears unmaintained and has more dependencies than necessary; therefore, a new crate could prove useful for other people. For `flowy`, the main benefits are improved compile times and a more modular code base.

I don't know how the crate should be called.

If someone other than me wants to implement this, you might find the [chapter about workspaces](https://doc.rust-lang.org/cargo/reference/workspaces.html) in the Cargo book useful.

**Comment by vineetred** [comment]
Now that the codebase has been modularised, extracting it into a new crate should not be that hard. We can do this soon. 

As for the name, ```wallpaper-rs``` sounds good.

@swagggpickle you think this can be worked up instead?

**Comment by vineetred** [comment]
Also, we need to decide if the new wallpaper crate will need it's own repo or we continue using this for it.

**Comment by mloehnig** [comment]
@vineetred I will work on this.

**Comment by vineetred** [comment]
Assigning it to you.
