### ISSUE TITLE
Use smaller HTTP library

### ISSUE THREAD

**Issue by Aloso** [vineetred/flowy#17]
Since only the blocking API of `reqwest` is used, it could be easily replaced with `ureq` to reduce the number of dependencies. `ureq` is very lightweight and offers several features to select only the required functionality. It is well tested and free of `unsafe`.

**Comment by vineetred** [comment]
I had asked on the Rust discord channel. Those guys just suggested I stick with ```reqwest```. However, it seems to make flowy a lot bulkier than required so I will be lookinginto this library. Thanks.

**Comment by vineetred** [comment]
Commit 52c82bf fixes this.
