### ISSUE TITLE
Refactor generate_config_solar function

### ISSUE THREAD

**Issue by vineetred** [vineetred/flowy#27]
**Describe the bug**
Refactor the ```generate_config_solar``` function in the file ```flowy/lib.rs```. The function is just a nightmare to look at in it's current state. While it gets the job done, it can also look nice while still doing its job.

**Comment by Baldomo** [comment]
@vineetred all the calculations done in [`generate_config_solar` L82-L88](https://github.com/vineetred/flowy/blob/2f7e73e8fac2d8d67c40b66137e3eaa5e81cce51/flowy/src/lib.rs#L82) can be simplified by just using the raw times in the timetable, there's no need of getting them in string format then converting them back to integers. For the same reason, all the night-duration and day-duration stuff can be done directly in `solar.rs`. I can make a quick PR to fix all of that if you wish

**Comment by vineetred** [comment]
@Baldomo go ahead. I was trying to do it myself but did not get around to it. Make a PR and I'll approve it.

**Comment by Baldomo** [comment]
Sure thing. But before approving, let me know if I have to fix anything related to my code, and note that `generate_config_solar` is not necessarily shorter now but it's (in my opinion) a lot cleaner (as nothing is mutable except `Vec`s)
