### ISSUE TITLE
Deb package installation fails

### ISSUE THREAD

**Issue by echeoquehaii** [vineetred/flowy#32]
Hi!
I was trying to install the .deb package and I got a strange bug.
Running the installation in terminal it seems to get stuck at this point: 

Configurazione` di flowy (0.2.5)...
+ echo enter dir
enter dir
+ read var1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by vineetred** [comment]
This isn't a bug -- flowy is asking you to enter the dir. Just enter the dir and you'll be good to go.

**Comment by echeoquehaii** [comment]
> This isn't a bug -- flowy is asking you to enter the dir. Just enter the dir and you'll be good to go.

OMG I can't believe this, I didn't notice! Sorry for that, such a noob...

**Comment by vineetred** [comment]
No worries. Happy to help!
