### ISSUE TITLE
Remove `clokwerk` dependency

### ISSUE THREAD

**Issue by Aloso** [vineetred/flowy#34]
With the `get_current_wallpaper_idx` function, we don't need `clokwerk` anymore. In the main loop, we can simply call `get_current_wallpaper_idx` and check if the returned index has changed since the last time.

To make this more efficient, times should be parsed ahead of time (using a `Vec<NaiveTime>` instead of `Vec<String>`).

Another possible optimization is to perform binary search instead of linear search in `get_current_wallpaper_idx`, although the number of wallpapers is likely never large enough that this matters.

Since `clokwerk` is a fairly small crate (its only dependency is `chrono`, which we use anyway), I understand if this is low priority.

**Comment by vineetred** [comment]
```clockwerk``` not only allows to easily schedule tasks but also lets flowy work as a daemon. Removing it would mean we come up with our own daemon as well. I'll see if I can get to this sometime in the future.

**Comment by Aloso** [comment]
I'm sorry I'm not following. The `set_times` function contains this code:

```rust
// set current wallpaper ...
// initialize scheduler ...
loop {
    scheduler.run_pending();
    // Listens every minute
    thread::sleep(Duration::from_secs(60));
}
```

which could be replaced with something like

```rust
let mut last_index = None;
loop {
    let index = get_current_wallpaper_idx(&times)?;
    if Some(index) != last_index {
        last_index = Some(index);
        desktop_envt.set_wallpaper(&walls[index])?;
    }
    // Listens every minute
    thread::sleep(Duration::from_secs(60));
}
```

**Comment by vineetred** [comment]
That is true, my bad. I just feel having clokwerk here makes the whole thing cleaner? Given that we are already using the main dependencies of clokwerk, I don't think we'll get a substantial performance boost either once it's removed. What do you think?

**Comment by Aloso** [comment]
Yes, the impact on compile times is probably negligible. I just think that we don't gain much by using it, and removing `clokwerk` might make the code simpler and easier to debug.

**Comment by vineetred** [comment]
Fair enough. For now, however, I think I would like flowy to stick with clokwerk just because it makes things look cleaner. However, I will let the issue stand as we will switch over some day

**Comment by vineetred** [comment]
Commit 6049b4a fixes this.
