### ISSUE TITLE
Add automated CI/CD pipeline to generate binaries

### ISSUE THREAD

**Issue by vineetred** [vineetred/flowy#37]
We already have a CI CD pipeline. I would like to edit this and automate the releases of binaries so that they are the most up to date versions of the source code.

**Comment by Celeo** [comment]
You could either use something like [auto](https://github.com/intuit/auto/) with [GHA integration](https://intuit.github.io/auto/docs/build-platforms/github-actions#ignite), or something like [this GHA addon](https://github.com/actions/upload-release-asset#example-workflow---upload-a-release-asset).

The former is intended to integrate with your releasing process and automate the release iteself, while the later would be triggered _by_ a release and add the binaries to the release.

**Comment by mayukhnair** [comment]
Hi! Noticed this was an open issue, authored an Actions workflow (PR #59) to get it done.

**Comment by vineetred** [comment]
PR #59 added this.
