### ISSUE TITLE
Unable to install it

### ISSUE THREAD

**Issue by ghost** [vineetred/flowy#41]
So I tried installing it, but after typing cargo install flowy I got stuck and I'm unable to proceed in the installation. If anyone could help me that would be great

**Comment by vineetred** [comment]
Give me more information? What is the exact error that the machine is throwing, what environment you use so and so forth. Use the template the next time.

**Comment by ghost** [comment]
so here's what I did:
i copied " cargo install flowy " into the terminal
it recommended me to install cargo
I typed  " sudo apt install cargo "
and then " cargo install flowy "
then I tried typing "flowy -d" into the terminal 
flowy not found did you mean flow6
I cd ed into the folder flowy is located and the same thing hapened

**Comment by vineetred** [comment]
It seems like flowy didn't get installed to path. Try restarting the terminal and run the command again. 

If this fails too, just grab the precompiled binary from the releases section.

**Comment by ghost** [comment]
Updating crates.io index
     Ignored package `flowy v0.3.0` is already installed, use --force to override
warning: be sure to add `/home/maximilian/.cargo/bin` to your PATH to be able to run the installed binaries

**Comment by vineetred** [comment]
> ```
> warning: be sure to add `/home/maximilian/.cargo/bin` to your PATH to be able to run the installed binaries
> ```
Exactly, cargo is telling  you what to do. Just add the above bit to your path and you should be able to run it.

**Comment by ghost** [comment]
what is the exact command 
I've already tried cd

**Comment by vineetred** [comment]
Just download the binary -- this will be easier. Give it permission by running ```chmod +x the_name_of_the_binary``` and it'll run as an executable after this.

Also, as this is the issue section for Flowy, I suggest we only stick to issues related to flowy and not on UNIX commands. I am closing the issue for now. If you still have a flowy related problem, do post here and the issue will be reopened.
