### ISSUE TITLE
strip_prefix unstable

### ISSUE THREAD

**Issue by vineetred** [vineetred/flowy#44]
**Describe the bug**
In PR #43 submitted by @Baldomo -- we use a Rust method ```strip_prefix```. This method was deemed [unstable](https://github.com/rust-lang/rust/issues/67302). We should stick to safe code

**Expected behavior**
Ideally, functionality preserving solution that does not use this method.

**Comment by Baldomo** [comment]
I believe the `strip_*` methods have been stabilised in rust 1.45.0 [as per the source code here](https://doc.rust-lang.org/src/core/str/mod.rs.html#4060-4063)

**Comment by vineetred** [comment]
Crap! I need update Rust then. Closing the issue.
