### ISSUE TITLE
Flowy doesn't work on Openbox on Arch Linux

### ISSUE THREAD

**Issue by gamehelp16** [vineetred/flowy#47]
**Describe the bug:**
I'm using openbox on Arch and flowy doesn't seem to support it.

**To Reproduce:**
1. Run `./flowy -d <dir name>` on openbox
2. See error

**Expected Behavior:**
Wallpaper should be changed.

**Desktop:**
 - Openbox on Arch Linux

**Additional context**
Here's the error message produced:
`thread 'main' panicked at 'Desktop envt could not be determined: NotPresent', flowy/src/lib.rs:163:24`

I have also tried some things such as setting the environment variable `XDG_CURRENT_DESKTOP` before running flowy:
- Running `env XDG_CURRENT_DESKTOP=openbox ./flowy -d <dir name>` gives `thread 'main' panicked at 'Unsupported Desktop Environment', wallpaper_rs/src/linux.rs:34:22`.
- Running `env XDG_CURRENT_DESKTOP=i3 ./flowy -d <dir name>` (I "lied" about my WM) doesn't produce any error, however the console output is stuck at `<--- Daemon Listening --->` and my wallpaper doesn't change (even though I already have `feh` installed).

**Comment by vineetred** [comment]
Currently, flowy does not support Openbox.

However, I'll add it soon. Will keep the issue open until then.

**Comment by joseildofilho** [comment]
Hi, which program does OpenBox uses for set you background, cause, if it's feh, one can try set as bspwm.

**Comment by gamehelp16** [comment]
I use feh to change my background on openbox. When I try running `env XDG_CURRENT_DESKTOP=bspwm ./flowy -d <dir name>`, the console output is stuck at `<--- Daemon Listening --->` and my wallpaper doesn't change (the exact same results as when running flowy with `XDG_CURRENT_DESKTOP` set to i3).

**Comment by joseildofilho** [comment]
hi, i tried to run, and i get the same as you, so, i had dived into the code, and I found that the rust didn't find the file, cause it was getting the following path: file://./lake (i downloaded the lake file and had put inside the project), so to solve it i tried flowy -d $(pwd)/lake.
PS: one can set as the DE as I3 or BSPWM, both use the same path, feh.

**Comment by vineetred** [comment]
> put inside the project), so to solve it i tried flowy -d $(pwd)/lake.

This is very interesting. Does it now work?

**Comment by gamehelp16** [comment]
> hi, i tried to run, and i get the same as you, so, i had dived into the code, and I found that the rust didn't find the file, cause it was getting the following path: file://./lake (i downloaded the lake file and had put inside the project), so to solve it i tried flowy -d $(pwd)/lake.
> PS: one can set as the DE as I3 or BSPWM, both use the same path, feh.

This worked like a charm, thank you!

**Comment by hektor** [comment]
> hi, i tried to run, and i get the same as you, so, i had dived into the code, and I found that the rust didn't find the file, cause it was getting the following path: file://./lake (i downloaded the lake file and had put inside the project), so to solve it i tried flowy -d $(pwd)/lake.
> PS: one can set as the DE as I3 or BSPWM, both use the same path, feh.

Did the trick in dwm too. 
Setting my `XDG_CURRENT_DESKTOP` to `i3` before running `flowy -p lake`
while having feh installed.
