### ISSUE TITLE
Flowy won't start as a systemd automated process

### ISSUE THREAD

**Issue by KosenJPG** [vineetred/flowy#48]
Laptop running on Manjaro.

Didn't have cargo installed so I went `pacman -S cargo` ; once cargo got installed I followed the readme `cargo install flowy` ; I then added `.cargo/bin` to my `$PATH` so that I could run flowy into my command line and everything worked fine.

When I tried making flowy a systemd automated process (once again following the readme), I got this error when trying to run flowy.service:
`
Failed to start flowy.service: Unit flowy.service has a bad unit file setting.
See user logs and 'systemctl --user status flowy.service' for details.
`
`systemctl --user status flowy.service` outputs: 
`
août 06 15:40:54 smooshy systemd[950]: /etc/xdg/systemd/user/flowy.service:6: Executable "-dir" not found in path "/usr/local/bin:/usr/bin", ignoring
août 06 15:40:54 smooshy systemd[950]: flowy.service: Service has no ExecStart=, ExecStop=, or SuccessAction=. Refusing.
`

**Comment by vineetred** [comment]
Can you post the contents of your ```flowy.service``` file?

**Comment by KosenJPG** [comment]
```
Description=flowy

[Service]
Environment=XDG_CURRENT_DESKTOP=KDE
ExecStart=--dir /home/kosen/Images/flowywalls/spiritedaway

[Install]
WantedBy=multi-user.target
```

**Comment by vineetred** [comment]
I see the issue - you're never starting flowy! 

So under the line where it says ```ExecStart=``` you must have the entire flowy command here. For example, in your case, that line would become ```ExecStart= flowy --dir /home/kosen/Images/flowywalls/spiritedaway```.

Your service file never knew what program to start.

**Comment by KosenJPG** [comment]
Yeah I tried that but I also have the same error : 
```

août 06 20:31:14 smooshy systemd[950]: /etc/xdg/systemd/user/flowy.service:6: Executable "flowy" not found in path "/usr/local/bin:/usr/bin"
août 06 20:31:14 smooshy systemd[950]: flowy.service: Unit configuration has fatal error, unit will not be started.

```

**Comment by vineetred** [comment]
Seems like flowy isn't in your path. Can you try adding it manually by download the appropriate binary from the releases section? Should work then.

**Comment by ventaquil** [comment]
@KosenJPG I think that problem is with your `PATH` variable.

Error suggests that your `PATH` contains only `/usr/local/bin:/usr/bin` but as a user you probably have `$HOME/.cargo` too.

My suggestion is to install flowy under `/usr/bin` directory. Everything should be fine then.

**Comment by KosenJPG** [comment]
> @KosenJPG I think that problem is with your `PATH` variable.
> 
> Error suggests that your `PATH` contains only `/usr/local/bin:/usr/bin` but as a user you probably have `$HOME/.cargo` too.
> 
> My suggestion is to install flowy under `/usr/bin` directory. Everything should be fine then.

@ventaquil yeah that's exactly my issue, but how can I install flowy under `/usr/bin`? When I follow the procedure it automatically installs it under `/.cargo`

**Comment by ventaquil** [comment]
> @ventaquil yeah that's exactly my issue, but how can I install flowy under `/usr/bin`? When I follow the procedure it automatically installs it under `/.cargo`

How about `--root` option?

    $ cargo install --root=/usr/local/ flowy
    ....
       Compiling flowy v0.3.3
        Finished release [optimized] target(s) in 3m 11s
      Installing /usr/local/bin/flowy
       Installed package `flowy v0.3.3` (executable `flowy`)
    $ find / -name flowy
    /usr/local/bin/flowy

Here you have installation directory order: [cargo install (docs)](https://doc.rust-lang.org/cargo/commands/cargo-install.html#cargo_install_description).

**Comment by KosenJPG** [comment]
@ventaquil Fixed! thank you!

**Comment by vineetred** [comment]
Closing the issue as it is fixed.
