### ISSUE TITLE
Move away demo folder from Master branch

### ISSUE THREAD

**Issue by knightpp** [vineetred/flowy#50]
### Problem
Building from Master branch requires downloading heavy .gif files.

### Solution
Move .gif files to the other branch or add gifs to a specially created Issue and link back to Readme.md.

I can do this if you want.

**Comment by vineetred** [comment]
Sure! Go ahead. Will approve the PR.

**Comment by knightpp** [comment]
Please create a new branch and push to the repo so I can create PR. I tried to attach gifs to an issue, but there is a limit on the uploads.
```git
git checkout --orphan images
git rm -rf .
```
