### ISSUE TITLE
[W10] unresolved import `wallpaper_rs::DesktopEnvt`

### ISSUE THREAD

**Issue by ghost** [vineetred/flowy#52]
Hi there, so i saw this project and thought it was cool so I tryed installing it and got this:

```

   Compiling flowy v0.3.3
error[E0432]: unresolved import `wallpaper_rs::DesktopEnvt`
  --> C:\Users\milan\.cargo\registry\src\github.com-1ecc6299db9ec823\flowy-0.3.3\src\lib.rs:10:29
   |
10 | use wallpaper_rs::{Desktop, DesktopEnvt};
   |                             ^^^^^^^^^^^ no `DesktopEnvt` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `flowy`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `flowy v0.3.3`, intermediate artifacts can be found at `C:\Users\milan\AppData\Local\Temp\cargo-installyVhPck`

Caused by:
  build failed
```

Now I am probably only one that actually tries to run this on windows so I am think this may not be something youre aware of.

**Comment by vineetred** [comment]
Very interesting! Could you tell me how you installed flowy? Also, it works well on W10 usually so not sure what is happening.

Also, you can just download the pre-compiled binary from the releases section. Just tested this method on a W10 PC and it works perfectly.

**Comment by ghost** [comment]
Yes, i realised after posting that pre-builds work.

I installed it standardly.
