### ISSUE TITLE
Flowy doesn't start at boot even after systemd --user enable flowy.service

### ISSUE THREAD

**Issue by BrachyKnight** [vineetred/flowy#53]
**Describe the bug**
Even after creating the file flowy.service in /etc/systemd/user and enabling it, after login the process is dead

**To Reproduce**
1. Create the file /etc/systemd/user/flowy.service
2. Write it like so: 
```
[Unit]
Description=flowy

[Service]
Environment=XDG_CURRENT_DESKTOP=GNOME
ExecStart=/home/user/.cargo/bin/flowy -p lake

[Install]
WantedBy=multi-user.target
```
3. Run `systemctl --user enable flowy.service`
4. After reboot the service isn't started, but it can be started with `systemctl --user start flowy.service`

**Expected behavior**
The service should start after boot with the unit file provided

**Desktop (please complete the following information):**
I am using Gnome Wayland on ArchLinux

**Comment by vineetred** [comment]
The unit file ensures that flowy runs in the background; not at boot.

**Comment by BrachyKnight** [comment]
@vineetred I tried modifying it but with no success. Is there a way to do so? Someone suggested adding `Type=oneshot` but it didn't work

**Comment by vineetred** [comment]
Sure there are loads of ways. This [tutorial ](https://www.linode.com/docs/quick-answers/linux/start-service-at-boot/)is one such way. 

Closing the issue as this is not relevant to flowy.
