### ISSUE TITLE
ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)

### ISSUE THREAD

**Issue by Dasemu** [vineetred/flowy#54]
**Describe the bug**
i started the script from using systmctl start An2Linux.service, the service start but dont show the notifications, here is the log.
● An2Linux.service - Run script at startup after network becomes reachable
     Loaded: loaded (/etc/systemd/system/An2Linux.service; disabled; vendor preset: enabled)
     Active: active (running) since Thu 2020-09-17 11:43:04 CEST; 2min 29s ago
   Main PID: 12737 (python3)
      Tasks: 2 (limit: 9381)
     Memory: 9.1M
     CGroup: /system.slice/An2Linux.service
             └─12737 python3 /home/dasemu/an2linuxserver-master/an2linuxserver.py

sep 17 11:43:04 Dasemu-PC systemd[1]: Started Run script at startup after network becomes reachable.
sep 17 11:43:05 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:43:05.036 root         INFO     Server certificate fingerprint: B7 40 C8 4C 1B AC D8 47 D9 50 3A 17 F9 B6 B4 A0 DF 8B 69 8D 33 5E 07>
sep 17 11:43:05 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:43:05.036 root         INFO     (TCP) Waiting for connections on port 46352 (an2linuxserver.py:850)
sep 17 11:43:09 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:43:09.444 root         ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)
sep 17 11:43:39 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:43:39.562 root         ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)
sep 17 11:43:45 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:43:45.869 root         ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)
sep 17 11:43:51 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:43:51.890 root         ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)
sep 17 11:44:33 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:44:33.706 root         ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)
sep 17 11:45:29 Dasemu-PC an2linuxserver.py[12737]: 2020-09-17 11:45:29.264 root         ERROR    (TCP) Failed TLS handshake notif_conn: Empty certificate data (an2linuxserver.py:231)
lines 1-18/18 (END)

**To Reproduce**
1. systemctl start An2Linux on PC
2. Click on 'test notification' in the mobile app
3. No notification
5. systemctl status An2Linux 

**Expected behavior**
It should show the notifications, if i open the script manually i get the expected behavior but if i use systemctl, no.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/32643260/93454912-edd66b00-f8db-11ea-8b2f-276bc4c50728.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint 20

**Comment by vineetred** [comment]
This is for flowy, the wallpaper application. Closed due to not being relevant.
