### ISSUE TITLE
Rebuild wallpaper_rs cargo package

### ISSUE THREAD

**Issue by JonaLoeffler** [vineetred/flowy#55]
Running flowy in i3wm still results in a kernel panic. I suppose this is because the wallpaper_rs cargo package has not been rebuilt yet. 
Could you please update the package to include the latest changes?

**Comment by vineetred** [comment]
Just checked -- seems like that is the issue. I am currently traveling, do you think is it possible for you to create a small PR?

**Comment by JonaLoeffler** [comment]
I'm not really this familiar with Rust/Cargo. Do I just have to set the version number in wallpaper_rs/Cargo.toml and flowy/Cargo.toml to 0.1.1 or is there more to it?

**Comment by vineetred** [comment]
Yep. That should be okay. The CI pipeline should generate the required binaries once done.
