### ISSUE TITLE
VirtualBox save state and restore causes black background

### ISSUE THREAD

**Issue by ventaquil** [vineetred/flowy#57]
**Describe the bug**
I have Ubuntu 20.04 virtual machine in VirtualBox. Sometimes after saving state of working machine and restoring later background is black.

**To Reproduce**
1. Create VirtualBox virtual machine with Ubuntu 20.04.
2. Install flowy.
3. Save state of working machine.
4. Restore state.
5. See an error.

**Expected behavior**
Normal background wallpaper.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Version 0.2.5
 - VirtualBox: 6.1.16

**Comment by vineetred** [comment]
Okay this seems to a bug when running flowy on VMs. However, I wasn't able to replicate it. Do you think you can provide me with the rust stacktrace/the errors you see?

**Comment by ventaquil** [comment]
Hey @vineetred, thanks for response.

I am trying to investigate it. Quick look shows that sometimes flowy service dies (I tried to get some logs but I don't see anything useful).

I am going to build it using debug target and run in a foreground, maybe this method is going to be more helpful.

**Comment by vineetred** [comment]
Sounds good! Let me know how that works out.

**Comment by ventaquil** [comment]
It seems that it's broken systemd service configuration. Sorry for the confusion.
