### ISSUE TITLE
Solar mode mode alternates day and night wallpapers twice per day

### ISSUE THREAD

**Issue by MidnessX** [vineetred/flowy#58]
**Description**
Solar mode mode alternates day and night wallpapers twice per day on Windows.

**To Reproduce**
Using a folder with two wallpapers, one named "DAY-1.jpg" and one named "NIGHT-2.jpg", run flowy in solar mode providing latitude and longitude.
Flowy will output four different times of day and four wallpapers: it will be "DAY-1.jpg", "NIGHT-2.jpg", "DAY-1.jpg", "NIGHT-2.jpg".

e.g.
.\flowy.exe --solar "D:/Pictures/Wallpapers/Test/" 47.10 9.61

**System info:**
 - OS:  Windows 10 release 20H2
 - Version 0.3.2

**Comment by vineetred** [comment]
Hey! Does this still happen? If I'm not wrong, flowy needs atleast 4 wallpapers to work as expected in the Solar mode. Try this and let me know what happens!

**Comment by MidnessX** [comment]
Hi,
Unfortunately yes, it still does occur!
I've tried using four different wallpapers (DAY-01.jpg, DAY-02.jpg, NIGHT-01.jpg, NIGHT-02.jpg) but to no avail since I still get a schedule where the sequence is repeated twice.

I've also noticed that the program fails to parse arguments if I write the path using backslashes as would be normal on Windows.
Some quirks while listing the content of the folder on a Windows platform, perhaps?

**Comment by vineetred** [comment]
Interesting! Let me take a look at this right away. 

Yep -- the Windows file listing behaves weirdly at times. If possible, I'd say stick to the UNIX naming schema. I'll make a note of this, for now, on the README.

**Comment by vineetred** [comment]
Commit 5e7bf728f69348c63874448dc9484be1411748aa should fix this. @MidnessX let me know if it still persists.

**Comment by MidnessX** [comment]
Just letting you know everything works fine now, thanks!
