### ISSUE TITLE
Refactor the codebase to handle expansion

### ISSUE THREAD

**Issue by vineetred** [vineetred/flowy#6]
**Is your feature request related to a problem? Please describe.**
The ```get``` and ```set``` wallpaper functions are very messy currently as they have to handle multiple OSes. 

**Describe the solution you'd like**
 Check desktop once and use enum type from there on out ```(match Some(enum))```.

**Additional context**
The config file, ```times.toml``` must be edited for this as well as ```struct Config``` in ```lib.rs```

**Comment by mloehnig** [comment]
There seems to be another create that provides the `get` and `set` wallpaper functionality. https://docs.rs/wallpaper/2.0.1/wallpaper/

But if you would like to recreate this crate I would be happy to assist.

**Comment by vineetred** [comment]
@swagggpickle So I did look at this crate when I was building flowy. However, I thought the contents could be easily reproducible in this codebase itself and avoid having to import extra crates. As you can see, I've implemented a few methods from that crate already in flowy.

So I suggest we just recreate it here. So yes, would love to get your help on it. What do you suggest we start with?

**Comment by vineetred** [comment]
@swagggpickle So I did look at this crate when I was building flowy. However, I thought the contents could be easily reproducible in this codebase itself and _avoid_ having to import extra crates. As you can see, I've implemented a few methods from that crate already in flowy.

So I suggest we just recreate it here. So _yes_, would love to get your help on it. My main priority is the refactor the ```set``` and ```get``` wallpaper functions so that they don't look so cluttered anymore. Do you think you can help with this?

**Comment by Aloso** [comment]
I'd like to point out that the `wallpaper` crate looks unmaintained. The last commit was over a year ago, and issues that were reported since then have been ignored.

It would be nice if `flowy` was split into two crates, one for the CLI and one for setting wallpapers. The latter would be an alternative for the existing `wallpaper` crate, but well maintained and with fewer dependencies.

**Comment by vineetred** [comment]
This would be the most ideal setup. However, I will take a bit longer as I am already working on another feature. If either of you want to begin working on that, it would be great.

**Comment by Aloso** [comment]
I'll create a separate issue to continue discussion there.

**Comment by mloehnig** [comment]
@vineetred Yes I think I can help with refactoring the existing `set` and `get` functions.

**Comment by Aloso** [comment]
@swagggpickle I didn't see that you wanted to implement this and already created a PR for it, sorry!

**Comment by vineetred** [comment]
@swagggpickle seems like this issue is sorted. Let me know if would like to contribute to other aspects of the code? Issue #15 wants to take the wallpaper codebase and make it into another crate. Do you think you can do this?
