### ISSUE TITLE
build failed - compilation error

### ISSUE THREAD

**Issue by Yeethaven** [vineetred/flowy#66]
**Describe the bug**
When I try to install flowy using `cargo install flowy`, the build fails with the following output:

```
   Compiling clap v3.0.13
   Compiling chrono v0.4.19
error[E0658]: arbitrary expressions in key-value attributes are unstable
 --> /home/hoven/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-3.0.13/src/lib.rs:8:39
  |
8 | #![cfg_attr(feature = "derive", doc = include_str!("../README.md"))]
  |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information

   Compiling url v2.2.2
error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `clap`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `flowy v0.4.0`, intermediate artifacts can be found at `/tmp/cargo-installYXCvki`

Caused by:
  build failed
```

**To Reproduce**
Use `cargo install flowy` on Linux Mint 20.3  x86_64 Cinnamon

**Expected behavior**
flowy should be downloaded and compiled by cargo.

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 x86_64 Cinnamon

**Comment by Yeethaven** [comment]
Update: downloading the binary from releases works as an alternative, but I still can't build flowy myself

**Comment by vineetred** [comment]
@Yeethaven sorry about the delayed response; were you able to build it later? I just tried to build on my local and everything went fine. Let me know if that's not the case with you?
