### ISSUE TITLE
Change GTK theme based on time of day

### ISSUE THREAD

**Issue by mmstick** [vineetred/flowy#7]
In the example of Pop!_OS, we have dark and light variants of our theme. It's been a commonly-requested feature to support alternating between them based on time of day. A light theme during the day, and a dark theme at night.

**Comment by vineetred** [comment]
Just for clarification, the feature requested is that there be different set of folders for the day and different for the night. Is this correct @mmstick?

**Comment by mmstick** [comment]
No, the change would be using `gio.Settings` to set the GTK theme. For example, say that your active theme is `PopOS`. At night, you'd want this to change to `PopOS-dark`. During the day, change it to `PopOS`.

**Comment by vineetred** [comment]
Got it. Sounds like a good addition so will be adding this to the todo. Do contribute too if you can!

**Comment by Aloso** [comment]
To me this sounds unrelated to wallpapers, so it might be better to use a separate tool for this. I prefer when a tool only does one thing, but does it very well.

I found the tool [AutomaThemely](https://github.com/C2N14/AutomaThemely) on Google.

**Comment by vineetred** [comment]
@mmstick what are your thoughts on this?
