### ISSUE TITLE
Support KDE

### ISSUE THREAD

**Issue by Aloso** [vineetred/flowy#8]
I use KDE and would like to use this tool. However, KDE is not supported according to the README.

**Comment by vineetred** [comment]
Hey @Aloso! So I tried building it but I had no way to test it so had to shelf it for now. But since all the low level functions are already implemented, it should be done fairly quick.

Do let me know if you're down to help.

**Comment by vineetred** [comment]
@Aloso added KDE support in the latest release. Let me know how it performs and file reports if there are any bugs that you encouter.

**Comment by vineetred** [comment]
@Aloso added KDE support in the latest release. Let me know how it performs and file reports if there are any bugs that you encouter.

**Comment by Aloso** [comment]
Thanks for adding KDE support! I tested it and it works. In some cases it can panic, which I fixed in #12.
