### ISSUE TITLE
Function to GET Sunset and Sunrise times

### ISSUE THREAD

**Issue by vineetred** [vineetred/flowy#9]
**Is your feature request related to a problem? Please describe.**
Need a function that can contact the ```sunrise-sunset.org``` API to get the sunset and sunrise times.  

**Describe the solution you'd like**
Ideally a function which takes the coordinates as the argument and returns the sunset and sunrise times.

**Additional context**
Let's stick to using the ```Reqwest``` module as it is already being used.

**Comment by Aloso** [comment]
What's the purpose of this? Is this intended for #7?

**Comment by vineetred** [comment]
@Aloso yes.

**Comment by vineetred** [comment]
@Aloso no, this is for Issue #4

**Comment by Baldomo** [comment]
@vineetred instead of relying on external online services [redshift's sun elevation module](https://github.com/jonls/redshift/blob/master/src/solar.c) can be easily ported into Rust

**Comment by vineetred** [comment]
@Baldomo it's just a lot more work porting a module than using an external online service. However, if you have other alternatives, happy to hear about it.

**Comment by Baldomo** [comment]
@vineetred I ported the code in rust and the accuracy test I wrote for the most important functions all pass. Please check it out

https://gist.github.com/Baldomo/11d3218b2ddf9b0c66a8cabc353a0bc6

There are some unneeded functions but this is just a literal translation of the original C code in idiomatic Rust. This module/file will never need maintenance because it only provides arithmetic functions to calculate the Sun's position. I think it's a compact and privacy-respecting alternative to using an external service

**Comment by vineetred** [comment]
@Baldomo this is brilliant! Does the code follow the same specification/API parameters as the C version?

**Comment by Baldomo** [comment]
Yes, I just translated it and added some more explanations to the original comments

**Comment by vineetred** [comment]
@Baldomo Why don't you publish this as a crate? It would be great if others can use it as well. I can help you with this if needed. Will allow easy import as well.

**Comment by Baldomo** [comment]
Honestly I don't really want to have to maintain a crate with this little functionality, it's totally fine to include the code in flowy though. And the gist will be indexed by search engines anyways so whoever looks for it will find it

**Comment by vineetred** [comment]
@Baldomo that makes sense. I'll try to incorporate this into flowy. Just to clarify -- which function in the ported version returns the sunset and sunrise times?

**Comment by Baldomo** [comment]
The file is currently missing a function which basically returns a `Map<SolarTime, f64>` filled with the absolute epoch times of the events given a latitude and longitude. I'll add it in the next 20 minutes or so

**Comment by vineetred** [comment]
@Baldomo that works. If you would like to contribute to this project directly, you can create a PR and I'll merge it.

**Comment by Baldomo** [comment]
Sure, I'll make a PR when I have time (currently studying for an exam which I'll have in a week)

**Comment by vineetred** [comment]
@Aloso do you think will be a good feature?

**Comment by Aloso** [comment]
In principle yes. One problem is that the sunrise and sunset time depends on your location. Most people don't know their coordinates by heart, so I can think of the following solutions:

1. flowy detects the coordinates automatically using the public IP address
    - they can be detected with `curl https://freegeoip.app/json/`
        - note this might not be very precise and doesn't work with a VPN
2. users can specify an address or postal code, and flowy uses an online service to find out the coordinates
3. users have to manually specify their coordinates; they can be looked up on openstreetmap

**Comment by vineetred** [comment]
Would asking the users to input the coordinates be not ideal even if we show the link from where they can find it?

**Comment by vineetred** [comment]
@swagggpickle what do you think of this?

**Comment by Baldomo** [comment]
@vineetred Redshift, f.lux and other similar apps just show the user where to get the coordinates and it's not a hassle for the devs or users honestly

**Comment by Baldomo** [comment]
flowy now has astronomical calculations :rocket:
